services:
  # Backend service
  - type: web
    name: rag-chatbot-backend
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: GOOGLE_API_KEY
        sync: false # Will prompt during deployment - NEVER commit actual key values
    autoDeploy: true

  # Frontend service
  - type: web
    name: rag-chatbot-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: rag-chatbot-backend
          envVarKey: RENDER_EXTERNAL_URL
    autoDeploy: true
