services:
  # Backend service
  - type: web
    name: rag-chatbot-backend
    runtime: python
    plan: free
    buildCommand: |
      mkdir -p uploads
      mkdir -p chroma_db
      mkdir -p vectors
      # Print Python version
      python --version
      # Use system packages to help with build
      pip install --upgrade pip
      # Install minimal dependencies first
      pip install -r requirements-minimal.txt
      # Install additional dependencies for main.py
      pip install langchain-google-genai==0.0.6 || echo "Failed to install langchain-google-genai"
      # Create a simple script to determine which app to run
      echo "cp main_minimal.py main_app.py" > choose_app.sh
      chmod +x choose_app.sh
      # Print installed packages for debugging
      pip list
    startCommand: uvicorn main_minimal:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 
