services:
  # Backend service
  - type: web
    name: rag-chatbot-backend
    runtime: python
    plan: free
    buildCommand: |
      mkdir -p uploads
      mkdir -p chroma_db
      mkdir -p vectors
      # Print Python version
      python --version
      # Use system packages to help with build
      pip install --upgrade pip
      # Install minimal dependencies
      pip install -r requirements-minimal.txt || (echo "Failed to install from requirements-minimal.txt, falling back to direct installation" && \
      pip install fastapi==0.104.1 uvicorn==0.22.0 python-multipart==0.0.6 sqlalchemy==2.0.23 python-dotenv==1.0.0 google-generativeai==0.3.2)
      # Print installed packages for debugging
      pip list
    startCommand: |
      if [ -f main.py ]; then
        uvicorn main:app --host 0.0.0.0 --port $PORT
      else
        uvicorn main_minimal:app --host 0.0.0.0 --port $PORT
      fi
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 
