services:
  # Backend service
  - type: web
    name: rag-chatbot-backend
    runtime: python
    plan: free
    buildCommand: |
      mkdir -p uploads
      mkdir -p chroma_db
      mkdir -p vectors
      pip install --upgrade pip wheel setuptools
      # Install numpy first and explicitly to avoid version conflicts
      pip install numpy==1.24.3
      # Install rest of dependencies
      pip install -r requirements-simple.txt
      # Print installed packages for debugging
      pip list
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 
